list(APPEND libmirs_srcs
	FwdOperProcess/FwdOperator.f90
	InversProcess/GeophCovBkg.f90
	InversProcess/SeFeErrCov.f90
	InversProcess/VarOprs.f90
	io/IO_Colocate.f90
	io/IO_DEP.f90
	io/IO_DropSonde.f90
	io/IO_InstrConfig.f90
	io/IO_MeasurData.f90
	io/IO_Misc.f90
	io/IO_Misc_LE.f90
	io/IO_Monitor.f90
	io/IO_Noise.f90
	io/IO_Regress.f90
	io/IO_Scene.f90
	io/IO_SFR.f90
	io/io_ssmis.f90
	math/mathFcts.f90
	misc/CntrlParams.f90
	misc/Consts.f90
	misc/misc.f90
	misc/TuningParams.f90
	#mspps/mspps.f90
	noise/Noise.f90
	PrePostProcess/PreClassif.f90
	qc/ErrorHandling.f90
	qc/QCchecking.f90
	utilities/utils.f90
   utilities/bias_NeuralNetwork.f90
	)

