list( APPEND crtm_libsrcs
	libsrc/ACCoeff_Binary_IO.f90
	libsrc/ACCoeff_Define.f90
	libsrc/ADA_Module.f90
	libsrc/AerosolCoeff_Binary_IO.f90
	libsrc/AerosolCoeff_Define.f90
	libsrc/ASvar_Define.f90
	libsrc/Azimuth_Emissivity_Module.f90
	libsrc/Binary_File_Utility.f90
	libsrc/CloudCoeff_Binary_IO.f90
	libsrc/CloudCoeff_Define.f90
	libsrc/Common_RTSolution.f90
	libsrc/Compare_Float_Numbers.f90
	libsrc/CRTM_Adjoint_Module.f90
	libsrc/CRTM_AerosolCoeff.f90
	libsrc/CRTM_Aerosol_Define.f90
	libsrc/CRTM_AerosolScatter.f90
	libsrc/CRTM_AncillaryInput_Define.f90
	libsrc/CRTM_AntennaCorrection.f90
	libsrc/CRTM_AOD_Module.f90
	libsrc/CRTM_AtmAbsorption.f90
	libsrc/CRTM_AtmOptics_Define.f90
	libsrc/CRTM_AtmOptics.f90
	libsrc/CRTM_Atmosphere_Define.f90
	libsrc/CRTM_Atmosphere.f90
	libsrc/CRTM_ChannelInfo_Define.f90
	libsrc/CRTM_CloudCoeff.f90
	libsrc/CRTM_Cloud_Define.f90
	libsrc/CRTM_CloudScatter.f90
	libsrc/CRTM_Fastem1.f90
	libsrc/CRTM_FastemX.f90
	libsrc/CRTM_Forward_Module.f90
	libsrc/CRTM_Geometry_Define.f90
	libsrc/CRTM_GeometryInfo_Define.f90
	libsrc/CRTM_GeometryInfo.f90
	libsrc/CRTM_Interpolation.f90
	libsrc/CRTM_IRiceCoeff.f90
	libsrc/CRTM_IR_Ice_SfcOptics.f90
	libsrc/CRTM_IRlandCoeff.f90
	libsrc/CRTM_IR_Land_SfcOptics.f90
	libsrc/CRTM_IRsnowCoeff.f90
	libsrc/CRTM_IR_Snow_SfcOptics.f90
	libsrc/CRTM_IRSSEM.f90
	libsrc/CRTM_IRwaterCoeff.f90
	libsrc/CRTM_IR_Water_SfcOptics.f90
	libsrc/CRTM_K_Matrix_Module.f90
	libsrc/CRTM_LifeCycle.f90
	libsrc/CRTM_LowFrequency_MWSSEM.f90
	libsrc/CRTM_Model_Profiles.f90
	libsrc/CRTM_Module.f90
	libsrc/CRTM_MoleculeScatter.f90
	libsrc/CRTM_MW_Ice_SfcOptics.f90
	libsrc/CRTM_MW_Land_SfcOptics.f90
	libsrc/CRTM_MW_Snow_SfcOptics.f90
	libsrc/CRTM_MWwaterCoeff.f90
	libsrc/CRTM_MW_Water_SfcOptics.f90
	libsrc/CRTM_NLTECorrection.f90
	libsrc/CRTM_Options_Define.f90
	libsrc/CRTM_Parameters.f90
	libsrc/CRTM_Planck_Functions.f90
	libsrc/CRTM_Predictor_Define.f90
	libsrc/CRTM_Predictor.f90
	libsrc/CRTM_RTSolution_Define.f90
	libsrc/CRTM_RTSolution.f90
	libsrc/CRTM_SEcategory.f90
	libsrc/CRTM_SensorData_Define.f90
	libsrc/CRTM_SensorInfo.f90
	libsrc/CRTM_SfcOptics_Define.f90
	libsrc/CRTM_SfcOptics.f90
	libsrc/CRTM_SpcCoeff.f90
	libsrc/CRTM_Surface_Define.f90
	libsrc/CRTM_Tangent_Linear_Module.f90
	libsrc/CRTM_TauCoeff.f90
	libsrc/CRTM_Utility.f90
	libsrc/CRTM_VISiceCoeff.f90
	libsrc/CRTM_VIS_Ice_SfcOptics.f90
	libsrc/CRTM_VISlandCoeff.f90
	libsrc/CRTM_VIS_Land_SfcOptics.f90
	libsrc/CRTM_VISsnowCoeff.f90
	libsrc/CRTM_VIS_Snow_SfcOptics.f90
	libsrc/CRTM_VISwaterCoeff.f90
	libsrc/CRTM_VIS_Water_SfcOptics.f90
	libsrc/CSvar_Define.f90
	libsrc/Date_Utility.f90
	libsrc/Ellison.f90
	libsrc/Emission_Module.f90
	libsrc/Endian_Utility.f90
	libsrc/File_Utility.f90
	libsrc/FitCoeff_Define.f90
	libsrc/FitCoeff_Destroy.inc
	libsrc/FitCoeff_Equal.inc
	libsrc/FitCoeff_Info.inc
	libsrc/FitCoeff_ReadFile.inc
	libsrc/FitCoeff_SetValue.inc
	libsrc/FitCoeff_WriteFile.inc
	libsrc/Foam_Utility_Module.f90
	libsrc/Fresnel.f90
	libsrc/Fundamental_Constants.f90
	libsrc/Guillou.f90
	libsrc/Hyperbolic_Step.f90
	libsrc/iAtm_Define.f90
	libsrc/IRwaterCoeff_Define.f90
	libsrc/Large_Scale_Correction_Module.f90
	libsrc/Liu.f90
	libsrc/LSEatlas_Define.f90
	libsrc/make.dependencies
	libsrc/makefile
	libsrc/make.filelist
	libsrc/Message_Handler.f90
	libsrc/MinMax_Find_Utility.f90
	libsrc/MWwaterCoeff_Define.f90
	libsrc/MWwaterLUT_Define.f90
	libsrc/NESDIS_AMSRE_SICEEM_Module.f90
	libsrc/NESDIS_AMSRE_SNOWEM_Module.f90
	libsrc/NESDIS_AMSU_SICEEM_Module.f90
	libsrc/NESDIS_AMSU_SnowEM_Module.f90
	libsrc/NESDIS_LandEM_Module.f90
	libsrc/NESDIS_MHS_SICEEM_Module.f90
	libsrc/NESDIS_MHS_SnowEM_Module.f90
	libsrc/NESDIS_SEAICE_PHYEM_MODULE.f90
	libsrc/NESDIS_SnowEM_Parameters.f90
	libsrc/NESDIS_SSMI_Module.f90
	libsrc/NESDIS_SSMI_SIceEM_Module.f90
	libsrc/NESDIS_SSMI_SnowEM_Module.f90
	libsrc/NESDIS_SSMIS_SeaIceEM_Module.f90
	libsrc/NESDIS_SSMIS_SnowEM_Module.f90
	libsrc/NLTECoeff_Binary_IO.f90
	libsrc/NLTECoeff_Define.f90
	libsrc/NLTE_Parameters.f90
	libsrc/NLTE_Predictor_Define.f90
	libsrc/NLTE_Predictor_IO.f90
	libsrc/ODAS_AtmAbsorption.f90
	libsrc/ODAS_Binary_IO.f90
	libsrc/ODAS_Define.f90
	libsrc/ODAS_Predictor_Define.f90
	libsrc/ODAS_Predictor.f90
	libsrc/ODAS_TauCoeff.f90
	libsrc/ODPS_AtmAbsorption.f90
	libsrc/ODPS_Binary_IO.f90
	libsrc/ODPS_CoordinateMapping.f90
	libsrc/ODPS_Define.f90
	libsrc/ODPS_Predictor_Define.f90
	libsrc/ODPS_Predictor.f90
	libsrc/ODPS_TauCoeff.f90
	libsrc/ODSSU_AtmAbsorption.f90
	libsrc/ODSSU_Binary_IO.f90
	libsrc/ODSSU_Define.f90
	libsrc/ODSSU_TauCoeff.f90
	libsrc/ODZeeman_AtmAbsorption.f90
	libsrc/ODZeeman_Predictor.f90
	libsrc/ODZeeman_TauCoeff.f90
	libsrc/PAFV_Define.f90
	libsrc/Profile_Utility_Parameters.f90
	libsrc/Reflection_Correction_Module.f90
	libsrc/RTV_Define.f90
	libsrc/Search_Utility.f90
	libsrc/SEcategory_Define.f90
	libsrc/SensorInfo_Parameters.f90
	libsrc/Slope_Variance.f90
	libsrc/Small_Scale_Correction_Module.f90
	libsrc/SOI_Module.f90
	libsrc/Sort_Utility.f90
	libsrc/SpcCoeff_Binary_IO.f90
	libsrc/SpcCoeff_Define.f90
	libsrc/Spectral_Units_Conversion.f90
	libsrc/SSU_Input_Define.f90
	libsrc/String_Utility.f90
	libsrc/Subset_Define.f90
	libsrc/TauCoeff_Define.f90
	libsrc/Timing_Utility.f90
	libsrc/Type_Kinds.f90
	libsrc/UnitTest_Define.f90
	libsrc/Zeeman_Input_Define.f90
	libsrc/Zeeman_Utility.f90
	)


