
if (INSTALL_DATA)
	install(DIRECTORY ${PROJECT_SOURCE_DIR}/data
		DESTINATION .
		COMPONENT Data
		)
endif()
install(DIRECTORY ${PROJECT_SOURCE_DIR}/doc
	DESTINATION .
	COMPONENT Documentation
	)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/gui
	DESTINATION .
	COMPONENT GUI
	)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/logs
	DESTINATION .
	COMPONENT Base
	)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/scripts
	DESTINATION .
	USE_SOURCE_PERMISSIONS
	COMPONENT Scripts
	)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/setup
	DESTINATION .
	COMPONENT Scripts
	USE_SOURCE_PERMISSIONS
	PATTERN "paths" EXCLUDE
	PATTERN "paths_idl.pro" EXCLUDE
	)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/src
	DESTINATION .
	COMPONENT Source
	)
install(FILES ${PROJECT_BINARY_DIR}/setup-install/paths
	DESTINATION setup
	COMPONENT Scripts
	)
install(FILES
	${PROJECT_SOURCE_DIR}/readme
	${PROJECT_SOURCE_DIR}/version.txt
	${PROJECT_SOURCE_DIR}/CMakeLists.txt
	${PROJECT_SOURCE_DIR}/repo-setup.sh
	${PROJECT_SOURCE_DIR}/configure-with-cmake.bash
	DESTINATION . COMPONENT Base)
install(DIRECTORY ${PROJECT_SOURCE_DIR}/cmake
	DESTINATION .
	COMPONENT Base
	)

